<?php

namespace ContainerIR9TKEs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreation3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.YK5gSqH.App\Entity\Creation' shared service.
     *
     * @return \App\Entity\Creation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.YK5gSqH": it references class "App\\Entity\\Creation" but no such service exists.');
    }
}
