<?php

namespace ContainerARxkVfO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KK5F_CzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KK5F.cz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KK5F.cz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'creation' => ['privates', '.errored..service_locator.KK5F.cz.App\\Entity\\Creation', NULL, 'Cannot autowire service ".service_locator.KK5F.cz": it references class "App\\Entity\\Creation" but no such service exists.'],
        ], [
            'creation' => 'App\\Entity\\Creation',
        ]);
    }
}
