<?php

namespace ContainerEMTVyTU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I6dCTOBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i6dCTOB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i6dCTOB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'creationRepository' => ['privates', 'App\\Repository\\CreationRepository', 'getCreationRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'creationRepository' => 'App\\Repository\\CreationRepository',
            'entityManager' => '?',
        ]);
    }
}
