<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2n5XfL3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2n5XfL3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2n5XfL3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2n5XfL3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2n5XfL3\App_KernelDevDebugContainer([
    'container.build_hash' => '2n5XfL3',
    'container.build_id' => '5e5ffeb1',
    'container.build_time' => 1733509024,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2n5XfL3');
