<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7a7noVm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7a7noVm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7a7noVm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7a7noVm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7a7noVm\App_KernelDevDebugContainer([
    'container.build_hash' => '7a7noVm',
    'container.build_id' => 'd122769d',
    'container.build_time' => 1734024326,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7a7noVm');
